print ("Hello - Zcin")
print ("Hello - Zcin pt 2")
print ("Hello - Mike")
print ("Hello - Zcin pt 3")
print ("Si Zcin naman daw mag merge")
print ("try ng stash")
print ("ako try ko naman po")
print ("hello si mich na magstash")
print ("hello im zen fr gitbash")
